name       : libgnomecanvas2
version    : 2.30.3
release    : 4
source     :
    - https://download.gnome.org/sources/libgnomecanvas/2.30/libgnomecanvas-2.30.3.tar.gz : a8ca85e734ab03ecf1fba7d99e01ae2541d0df539c69a7da9414cde928c116da
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : The libgnomecanvas package contains the GNOME canvas library.
description: |
    The libgnomecanvas package contains the GNOME canvas library. It is an engine for structured graphics and one of the essential GNOME libraries.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libart-2.0)
    - pkgconfig(libglade-2.0)
setup      : |
    %configure --enable-glade --disable-static
build      : |
    %make
install    : |
    %make_install
