name       : libgnomecanvas2
version    : 2.30.3
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgnomecanvas/2.30/libgnomecanvas-2.30.3.tar.bz2 : 859b78e08489fce4d5c15c676fec1cd79782f115f516e8ad8bed6abcb8dedd40
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.library
summary    : The libgnomecanvas package contains the GNOME canvas library.
description: |
    The libgnomecanvas package contains the GNOME canvas library. It is an engine for structured graphics and one of the essential GNOME libraries.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libart-2.0)
    - pkgconfig(libglade-2.0)
setup      : |
    %configure --enable-glade --disable-static
build      : |
    %make
install    : |
    %make_install
