name       : libgnomecanvas2
version    : 1.104.0
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgnomecanvas2/1.104/libgnomecanvas2-1.104.0.tar.gz : 8d8c6224029818e44d9050b194065766761a51ebd30fd4a16e61ebdeba5234cc
license    :
    - GPL-2.0
    - LGPL-2.0
summary    : The libgnomecanvas package contains the GNOME canvas library.
description: |
    The libgnomecanvas package contains the GNOME canvas library. It is an engine for structured graphics and one of the essential GNOME libraries.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libart-2.0)
    - pkgconfig(libglade-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
